pre-commit:
  commands:
    fmt:
      run: deno task fmt {staged_files} && git update-index --again
    lint:
      run: deno task lint {staged_files}
pre-push:
  follow: true
  commands:
    test:
      run: deno task test