pre-commit:
  commands:
    fmt:
      run: deno task fmt {staged_files} && git update-index --again
    lint:
      run: deno task lint {staged_files}
pre-push:
  commands:
    test:
      glob: "*.test.ts"
      run: deno test -A {all_files}
