name: Build
run-name: Build
on:
  pull_request:
    type: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Format check
        run: "deno task fmt-check"
      
      - name: Lint
        run: "deno task lint"

      - name: Test
        run: "deno task test"