name: Lint
run-name: Running format and lint commands
on:
  pull_request:
    type: [opened, synchronize, reopened]
jobs:
  build:
    uses: ./.github/workflows/build.yml
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Format check step
        run: "deno task fmt-check"
      
      - name: Lint step
        run: "deno task lint"
