name: Test
run-name: Running test command
on:
  pull_request:
    type: [opened, synchronize, reopened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        uses: .github/actions/build.yml

      - name: Test step
        run: "deno task test"
