name: Test
run-name: Running test command
on:
  pull_request:
    type: [opened, synchronize, reopened]
jobs:
  build:
    uses: ./.github/workflows/build.yml
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: "deno task test"
